version: 2

# 🟤 BRONZE (Sources)
sources:
  - name: bronze
    database: KRISHNA_SOURCE
    schema: bronze

    tables:
      - name: customers_raw
        loaded_at_field: created_at
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}

      - name: orders_raw
        loaded_at_field: order_date
        freshness:
          warn_after: {count: 1, period: day}
          error_after: {count: 2, period: day}

# 🥈 SILVER
models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          # - unique   ❌ disabled (duplicates)

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          # - relationships:   ❌ disabled (orphan records)
          #     to: ref('stg_customers')
          #     field: customer_id

# 🥇 GOLD
  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - not_null
          # - unique   ❌ disabled (duplicates)

  - name: customer_revenue
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique